name: allelefinder_env
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - blast=2.17.0=h66d330f_0
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - curl=8.17.0=h4e3cde8_0
  - entrez-direct=24.0=he881be0_0
  - gmap=2025.07.31=pl5321hb1d24b7_1
  - icu=75.1=he02047a_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.45=bootstrap_ha15bf96_3
  - libcurl=8.17.0=h4e3cde8_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgomp=15.2.0=h767d61c_7
  - libidn2=2.3.8=hfac485b_1
  - liblzma=5.8.1=hb9d3cd8_2
  - libmpdec=4.0.0=hb9d3cd8_0
  - libnghttp2=1.67.0=had1ee68_0
  - libsqlite=3.51.0=hee844dc_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.41.2=he9a06e4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - mcscanx=1.0.0=h9948957_0
  - ncbi-vdb=3.2.1=h9948957_0
  - ncurses=6.5=h2d0b736_3
  - openssl=3.6.0=h26f9b46_0
  - pcre2=10.45=hc749103_0
  - perl=5.32.1=7_hd590300_perl5
  - perl-archive-tar=3.04=pl5321hdfd78af_0
  - perl-carp=1.50=pl5321hd8ed1ab_0
  - perl-common-sense=3.75=pl5321hd8ed1ab_0
  - perl-compress-raw-bzip2=2.214=pl5321hda65f42_0
  - perl-compress-raw-zlib=2.214=pl5321h4dac143_0
  - perl-constant=1.33=pl5321hd8ed1ab_0
  - perl-encode=3.21=pl5321hb9d3cd8_1
  - perl-exporter=5.74=pl5321hd8ed1ab_0
  - perl-exporter-tiny=1.002002=pl5321hd8ed1ab_0
  - perl-extutils-makemaker=7.70=pl5321hd8ed1ab_0
  - perl-file-util=4.201720=pl5321hdfd78af_0
  - perl-io-compress=2.213=pl5321h503566f_0
  - perl-io-zlib=1.15=pl5321hdfd78af_1
  - perl-json=4.10=pl5321hdfd78af_1
  - perl-json-xs=4.04=pl5321h9948957_0
  - perl-lib=0.63=pl5321hd8ed1ab_0
  - perl-list-moreutils=0.430=pl5321hdfd78af_0
  - perl-list-moreutils-xs=0.430=pl5321h7b50bb2_5
  - perl-parent=0.243=pl5321hd8ed1ab_0
  - perl-pathtools=3.75=pl5321hb9d3cd8_2
  - perl-scalar-list-utils=1.70=pl5321hb03c661_0
  - perl-storable=3.15=pl5321hb9d3cd8_2
  - perl-types-serialiser=1.01=pl5321hdfd78af_0
  - pip=25.3=pyh145f28c_0
  - python=3.14.0=h32b2ec7_102_cp314
  - python_abi=3.14=8_cp314
  - readline=8.2=h8c095d6_2
  - tk=8.6.13=noxft_ha0e22de_103
  - tzdata=2025b=h78e105d_0
  - wget=1.25.0=hc2d8bac_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.7=hb8e6e7a_2
